### PR TITLE
fix: reuse tx for relation join

### LINKED ISSUE #364: Select with `HasMany` and `ManyToMany` does not use current transaction
When performing a join on a `HasMany` or `ManyToMany` relation, bun starts a new select query as such:

https://github.com/uptrace/bun/blob/25ac1477f98451c0974dc3b57a5af1e91b863676/query_select.go#L346-L349

Unfortunately creating the new query via `q.db` ignores whether `q.conn` might be a `*sql.Tx`, which can break code that performs this join during a transaction. Using `q.db` creates a new connection to perform the query, which will break queries that select data created or modified during a transaction.

### PR DESCRIPTION
**Pull request by sbward**
Fixes #364

- Minimal change for reusing an existing transaction when joining relations.
- (Minor) Fixes `IDB`/`IConn` interface checking and comments.

### CODE REVIEW

File: query_select.go [hunk 1]
```diff
@@ -344,9 +344,9 @@ func (q *SelectQuery) selectJoins(ctx context.Context, joins []relationJoin) err
 		case schema.HasOneRelation, schema.BelongsToRelation:
 			err = q.selectJoins(ctx, j.JoinModel.getJoins())
 		case schema.HasManyRelation:
-			err = j.selectMany(ctx, q.db.NewSelect())
+			err = j.selectMany(ctx, q.idb(ctx).NewSelect())
 		case schema.ManyToManyRelation:
-			err = j.selectM2M(ctx, q.db.NewSelect())
+			err = j.selectM2M(ctx, q.idb(ctx).NewSelect())
```
Comment (vmihailenco) [inline query_select.go:349]: What about `q.db.NewSelect().Conn(q.conn)`?

File: query_base.go [hunk 2]
```diff
@@ -60,9 +60,8 @@ type IDB interface {
 }
 
 var (
-	_ IConn = (*DB)(nil)
-	_ IConn = (*Conn)(nil)
-	_ IConn = (*Tx)(nil)
+	_ IDB = (*DB)(nil)
+	_ IDB = Tx{}
```
Comment (vmihailenco) [inline query_base.go:64]: This used to work before. Probably should be reverted.

File: query_select.go (hunk 1 above)
Comment (sbward) [reply query_select.go]: 👍
