### PR TITLE
fix: allow Limit() without Order() with MSSQL

### LINKED ISSUE #811: Erro dialect mssql witch NEXT in the FETCH
in import i use:
```
_ "github.com/denisenkom/go-mssqldb"
"github.com/uptrace/bun"
"github.com/uptrace/bun/dialect/mssqldialect"
```
function i use:
```
func (i *Inventario) GetFistThreeItens(db *bun.DB, cnpj string, ano int) ([]models.Inventario, error) {
	var itens []models.Inventario
	err := db.NewSelect().Model(&itens).Where("cnpj = ? and ano = ?", cnpj, ano).Limit(3).Scan(context.Background())
	if err != nil {
		return nil, err
	}
	return itens, nil
}
```
recive erro return: mssql.Error: mssql: Invalid usage of the option NEXT in the FETCH statement

my microsoft sql server 2017

### PR DESCRIPTION
**Pull request by CL-Jeremy**
Implements workaround from https://stackoverflow.com/a/36156953 for all backends supporting `feature.OffsetFetch` from ISO/ANSI SQL:2008, which specifies `ORDER BY` as a requirement. This should be tested further if more backends are to be added (such as Oracle in #995 – this feature is not enable there, and there seems to be an impact noted by https://stackoverflow.com/q/48620590 and https://stackoverflow.com/q/59864964).

Closes #811

### CODE REVIEW

File: query_select.go [hunk 1]
```diff
@@ -538,6 +538,11 @@ func (q *SelectQuery) appendQuery(
 	if count && !cteCount {
 		b = append(b, "count(*)"...)
 	} else {
+		// Allows Limit() without Order() with MSSQL as per https://stackoverflow.com/a/36156953
+		if q.limit > 0 && fmter.Dialect().Features().Has(feature.OffsetFetch) && len(q.order) == 0 {
+			b = append(b, "0 AS _temp_sort, "...)
+			q.order = []schema.QueryWithArgs{schema.UnsafeIdent("_temp_sort")}
```
Comment (vmihailenco) [inline query_select.go:544]: This is query generation and it should not change the original `SelectQuery`, because someone may be reusing them.

You probably need to add another block of code to generate order without changing the `SelectQuery`.

Comment (CL-Jeremy) [reply query_select.go:544]: Do you mean that if I have a `SelectQuery` in a variable `a` and then do `b := a.Limit(5)`, the value of `a` would change, and that would be a problem? Isn't that also the case without the proposed change? I cannot seem to find an analog for this case to compare to. Do you mean something like `ORDER BY` after `LIMIT`, or is there another case where there could be something appended to a select query after `Limit()`? An example would be much appreciated.

Comment (vmihailenco) [reply query_select.go]: @CL-Jeremy I've fixed this myself. See the commits in this branch.
